FRT_COLUMNS = [

    'ODV',
    'DT',
    'DVFf1',
    'DVFf2',
    'DVFf3',
    'DVFm',
    'DVFsl',
    'DHPGrAvLo',
    'DHPGrAvMi',
    'DHPGrAvSh',
    'Date',
    'DCP',
    #'PriceOfDOLE',
    'ShareName',
    'ShareNumber',  # is actually the index
    '3jP',
    'V2d',
    '3nH',
    'Score',
    'BiggestMSm',
    'CV1',
    'DHP',
    'DHPlast20hi', 
    #'3. StjP1', 
    #'DjP',
    #'RbSDV.D-7÷RbSDV.D-4',
    'DateOfLastEntry',
    'Reminder',
    'Risk Size',
]

FRT_COLS_DIGITS = {
    'ODV': 0,
    'DT': 3,
    'DVFf1': 3,
    'DVFf2': 3,
    'DVFf3': 3,
    'DVFm': 3,
    'DVFsl': 3,
    'DHPGrAvLo': 3,
    'DHPGrAvMi': 3,
    'DHPGrAvSh': 3,
    'Date': 0,
    'DCP': 3,
    #'PriceOfDOLE': 3,
    'ShareName': 0,
    'ShareNumber': 0, 
    '3jP': 0,
    'V2d': 0,
    '3nH': 0,
    'Score': 0,
    'BiggestMSm': 3,
    'CV1': 3,
    'DHP': 3,
    'DHPlast20hi': 3, 
    #'3. StjP1', 
    #'DjP',
    #'RbSDV.D-7÷RbSDV.D-4',
    'Reminder': 0,
    'Risk Size': 0,
    'DateOfLastEntry': 0,
}

