''' column definitions for the overview '''

# OVERVIEW
# for calculations
#from bsbetl.alltable_calcs.M_DailyAveragePrice import M_DailyAveragePrice

OV_COLUMNS = [
    'Status',
    'Date',
    'ShareNumber',  # is actually the index
    'ShareName',
    'Lazy',
    'VP',
    'DCP',
    'DOP',
    'DOP.D-1',
    'DHP',
    'AvMV',
    'AvMVdec',
    'PSMV',

    'CV1',
    'CV1.D-1',
    'CV1.D-2',
    'CV1.D-3',
    'CV1.D-4',
    'CV1.D-5',

    'RCV1',
    'RCV1.D-1',
    'RCV1.D-2',
    'RCV1.D-3',
    'RCV1.D-4',
    'RCV1.D-5',
    'RCV1small',

    'DHP.D-1',
    'DHP.D-2',
    'DHP.D-3',
    'DHP.D-4',
    'DHP.D-5',
    'DHP.D-6',
    'DHP.D-7',
    'DHP.D-8',
    'DHP.D-9',
    'DLP',
    'DLOCP',
    'DLOCP.D-1',
    'DLOCP.D-2',
    'DLOCP.D-3',
    'DLOCP.D-4',
    'DLOCP.D-5',
    'DLOCP.D-6',
    'DLOCP.D-7',
    'DLOCP.D-8',
    'DLOCP.D-9',
    'DHOCP',
    'DMP',
    'DMP.D-1',
    'DMP.D-2',
    'DMP.D-3',
    'DT',
    'DT1',
    'SDT',
    'ODV',
    'DV',

    'bSDV',
    'RbSDV',
    'RbSDV.D-4',
    'RbSDV.D-7',

    'HBF',
    'DHPlasthi', 
    'DHPlasthi.D-1', 
    'DHPlasthi3perc', 
    'DHPlast3hi', 
    'DHPlasthi3perc.D-1', 
    'DHPlast20hi', 
    'DHPlast20hi3perc', 
    'DHPlast20hi.D-1', 
    'DHPbig',  
    'DLPsmall',
    'DaysDHPlasthi',
    'DaysDHPlast20hi',
    'DaysDHPlasthi3perc',
    'DHPGr',
    'DHPGrAvSh',
    'DHPGrAvSh.D-1',
    'DHPGrAvSh.D-2',
    'DHPGrAvMi',
    'DHPGrAvLo',
    'DHPGrDiSl',
    'DHPGrDiSl.D-1',
    'DHPGrDiF',
    'DHPGrDiF.D-1',
    'pnt1_DHPGrDiF',
    'pnt3_DHPGrDiF',
    'SDVBsl', 
    'SDVBm', 
    'SDVBf', 
    'SDVBf.D-1', # not used?
    'SDVBf.D-2', 
    'SDVCsl', 
    'SDVCm', 
    'SDVCf1', 
    'SDVCf2',
    'SDVCf2.D-1',
    #'DVFdf',
    'DVFf1',
    'DVFf2',
    'DVFf3',
    'DVFm',
    'DVFsl',
    'SRDHP1',
    'SRDHP2',
    'SRDHP3',
    'SRDHP4',
    'SRDHP5',
    'SRDHPGr1',
    'SRDHPGr2',
    'SRDHPGr3',
    'SRDHPGr4',
    'SDHP',
    'SDHPGr1sh',
    'SDHPGr1m',
    'SDHPGr1lo',
    'SDT1f',
    'SDT1sl',
    'DTF',
    'SDLOCPGrsl',
    'DLOCup',
    'SBr',
    'SBr.D-1',
    'SBr.D-2',
    'SBr.D-3',
    'SBr.D-4',
    'SBr.D-5',

    'DjP',

    'MSmp',
    'MSmpv',
    'MSmv',

    'DDHPlasthi',
    'DDHPlasthi3perc',
    'DDHPlast20hi',

]

# dash layout INITIAL
OV_COLUMNS_INITIAL = [
    'Status',
    'Date',
    'ShareNumber',
    'ShareName',
    #'Lazy',
    # 'VP',
    # 'DCP',
    # 'DT',
    # 'ODV',
    # 'DV',
    # 'AvMV',
    # 'PSMV',
]

# Dash layout full offering
OV_COLUMNS_DASH = [
    'Status',
    'Date',
    'ShareNumber',
    'ShareName',
    'Lazy',
    'VP',
    'DCP',
    'DOP',
    'DOP.D-1',
    'DHP',
    'AvMV',
    'AvMVdec',
    'PSMV',

    'CV1',
    'CV1.D-1',
    'CV1.D-2',
    'CV1.D-3',
    'CV1.D-4',
    'CV1.D-5',

    'RCV1',
    'RCV1.D-1',
    'RCV1.D-2',
    'RCV1.D-3',
    'RCV1.D-4',
    'RCV1.D-5',
    'RCV1small',

    'DHP.D-1',
    'DHP.D-2',
    'DHP.D-3',
    'DHP.D-4',
    'DHP.D-5',
    'DHP.D-6',
    'DHP.D-7',
    'DHP.D-8',
    'DHP.D-9',

    'DLP',
    'DLOCP',

    'DLOCP.D-1',
    'DLOCP.D-2',
    'DLOCP.D-3',

    'DLOCP.D-4',
    'DLOCP.D-5',
    'DLOCP.D-6',
    'DLOCP.D-7',
    'DLOCP.D-8',
    'DLOCP.D-9',

    'DHOCP',
    'DMP',

    'DMP.D-1',
    'DMP.D-2',
    'DMP.D-3',

    'DT',
    'DT1',
    'SDT',
    'ODV',
    'DV',
    'bSDV',
    'RbSDV',
    'RbSDV.D-4',
    'RbSDV.D-7',

    'HBF',
    'DHPlasthi',
    'DHPlasthi.D-1',
    'DHPlast3hi', 
    'DHPlasthi3perc',
    'DHPlasthi3perc.D-1',
    'DHPlast20hi', 
    'DHPlast20hi3perc', 
    'DHPlast20hi.D-1',
    'DHPbig',  
    'DLPsmall',
    'DaysDHPlasthi',
    'DaysDHPlast20hi',
    'DaysDHPlasthi3perc',
    'DHPGr',
    'DHPGrAvSh',

    'DHPGrAvSh.D-1',
    'DHPGrAvSh.D-2',

    'DHPGrAvMi',
    'DHPGrAvLo',
    'DHPGrDiSl',
    'DHPGrDiF',

    'DHPGrDiF.D-1',

    'pnt1_DHPGrDiF',
    'pnt3_DHPGrDiF',
    'SDVBsl', 
    'SDVBm', 
    
    'SDVBf', 
    'SDVBf.D-1', 
    'SDVBf.D-2', 

    'SDVCsl', 
    'SDVCm', 
    'SDVCf1', 
    
    'SDVCf2',
    'SDVCf2.D-1',

    #'DVFdf',
    'DVFf1',
    'DVFf2',
    'DVFf3',
    'DVFm',
    'DVFsl',
    'SRDHP1',
    'SRDHP2',
    'SRDHP3',
    'SRDHP4',
    'SRDHP5',
    'SRDHPGr1',
    'SRDHPGr2',
    'SRDHPGr3',
    'SRDHPGr4',
    'SDHPGr1sh',
    'SDHP',
    'SDHPGr1m',
    'SDHPGr1lo',
    'SDT1f',
    'SDT1sl',
    'DTF',
    'SDLOCPGrsl',
    'DLOCup'
    'SBr',

    'SBr.D-1',
    'SBr.D-2',
    'SBr.D-3',
    'SBr.D-4',
    'SBr.D-5',

    'DjP',

    'MSmp',
    'MSmpv',
    'MSmv',

    'DDHPlasthi',
    'DDHPlasthi3perc',
    'DDHPlast20hi',

]

# consult this to know which columns pair with which stage
OV_STAGE_TO_COLS = {
    # 1: ['Date', 'ShareNumber', 'ShareName', 'Lazy', 'VP', 'DCP', 'DOP','DHP', 'DT', 'ODV', 'DLP', 'DLOCP', 'DHOCP', 'DMP','DVFdf','DVFf1','DVFf2','DVFm','DVFsl',],
    # the second array below is a direct copy of M_DailyAveragePrice().ov_computeds
    # (we cannot reference it directly here since it would cause a circular import)

    # 1: ['Status','Date', 'ShareNumber', 'ShareName', 'Lazy', 'VP'] + ['DT','DT1','SDT','ODV','DHP','AvMV','PSMV', 'CV1','CV1.D-1','CV1.D-2','CV1.D-3','CV1.D-4','CV1.D-5','RCV1','RCV1.D-1','RCV1.D-2','RCV1.D-3','RCV1.D-4','RCV1.D-5','DHP.D-1','DHP.D-2','DHP.D-3','DHP.D-4','DHP.D-5','DHP.D-6','DHP.D-7','DHP.D-8','DHP.D-9','DLP','DLOCP','DLOCP.D-1','DLOCP.D-2','DLOCP.D-3','DLOCP.D-4','DLOCP.D-5','DLOCP.D-6','DLOCP.D-7','DLOCP.D-8','DLOCP.D-9','DHOCP','DMP','DMP.D-1','DMP.D-2','DMP.D-3','DCP','DOP','DOP.D-1','DHPbig','DLPsmall', 'MSmp', 'MSmpv', 'MSmv' ],   
    1: OV_COLUMNS,
    2: OV_COLUMNS, # iow all columns
    3: OV_COLUMNS,
    4: [],
}

OV_COLS_DIGITS = {
    'Status': 0,
    'Date': 0,
    'ShareNumber': 0,
    'ShareName': 0,
    'Lazy': 0,
    'VP': 1,
    'DCP': 3,
    'DOP': 3,
    'DOP.D-1': 3,
    'DHP': 3,
    'AvMV': 2,
    'AvMVdec':2,
    'PSMV': 1,

    'CV1': 2,
    'CV1.D-1': 2,
    'CV1.D-2': 2,
    'CV1.D-3': 2,
    'CV1.D-4': 2,
    'CV1.D-5': 2,

    'RCV1': 3,
    'RCV1.D-1': 3,
    'RCV1.D-2': 3,
    'RCV1.D-3': 3,
    'RCV1.D-4': 3,
    'RCV1.D-5': 3,
    'RCV1small': 3,

    'DHP.D-1': 3,
    'DHP.D-2': 3,
    'DHP.D-3': 3,
    'DHP.D-4': 3,
    'DHP.D-5': 3,
    'DHP.D-6': 3,
    'DHP.D-7': 3,
    'DHP.D-8': 3,
    'DHP.D-9': 3,

    'DLP': 3,
    'DLOCP': 3,

    'DLOCP.D-1': 3,
    'DLOCP.D-2': 3,
    'DLOCP.D-3': 3,
    'DLOCP.D-4': 3,
    'DLOCP.D-5': 3,
    'DLOCP.D-6': 3,
    'DLOCP.D-7': 3,
    'DLOCP.D-8': 3,
    'DLOCP.D-9': 3,  

    'DHOCP': 3,
    'DMP': 3,

    'DMP.D-1': 3,
    'DMP.D-2': 3,
    'DMP.D-3': 3,

    'DT': 3,
    'DT1': 3,
    'SDT': 2,
    'ODV': 0,
    'DV': 2,
    'bSDV': 3,
    'RbSDV': 3,
    'RbSDV.D-4': 3,
    'RbSDV.D-7': 3,

    'HBF': 2,
    'DHPlasthi': 3,
    'DHPlast3hi': 3, 
    'DHPlast20hi': 3,
    'DHPlast20hi3perc': 3, 
    'DHPlast20hi.D-1': 3,
    'DaysDHPlasthi': 0,
    'DaysDHPlast20hi': 0,
    'DaysDHPlasthi3perc': 0,
    'DHPlasthi3perc':3,
    'DHPlasthi3perc.D-1':3,  
    'DHPbig':3,  
    'DLPsmall': 3,
    'DHPGr': 3,
    'DHPGrAvSh': 4,

    'DHPGrAvSh.D-1': 4,
    'DHPGrAvSh.D-2': 4,

    'DHPGrAvMi': 4,
    'DHPGrAvLo': 4,
    'DHPGrDiSl': 4,
    'DHPGrDiF': 4,

    'DHPGrDiF.D-1': 4,

    'pnt1_DHPGrDiF': 4,
    'pnt3_DHPGrDiF': 4,
    'SDVBsl':2, 
    'SDVBm':2, 

    'SDVBf':2, 
    'SDVBf.D-1':2, 
    'SDVBf.D-2':2, 

    'SDVCsl':2, 
    'SDVCm':2, 
    'SDVCf1':2, 
    
    'SDVCf2':2,
    'SDVCf2.D-1':2,

    #'DVFdf': 3,
    'DVFf1': 3,
    'DVFf2': 3,
    'DVFf3': 3,
    'DVFm': 3,
    'DVFsl': 3,
    'SRDHP1': 3,
    'SRDHP2': 3,
    'SRDHP3': 3,
    'SRDHP4': 3,
    'SRDHP5': 3,
    'SRDHPGr1':3,
    'SRDHPGr2':3,
    'SRDHPGr3':3,
    'SRDHPGr4':3,
    'SDHP': 3,
    'SDHPGr1sh':4,
    'SDHPGr1m':4,
    'SDHPGr1lo':4,
    'SDT1f':3,
    'SDT1sl':3,
    'DTF':4,
    'SDLOCPGrsl': 4,
    'DLOCup': 0,
    'SBr':3,

    'SBr.D-1':3,
    'SBr.D-2':3,
    'SBr.D-3':3,
    'SBr.D-4':3,
    'SBr.D-5':3,

    'DjP': 0,

    'MSmp': 3,
    'MSmpv': 3,
    'MSmv': 3,

    '3jP': 0,
    '3V2d': 0,
    '3nH': 0,
    'Score': 0,

    'DDHPlasthi': 0,
    'DDHPlasthi3perc': 0,
    'DDHPlast20hi': 0,

}

OV_COLS_TIPS = {
    'Status': 'Status of last process-3 run',
    'Date': 'DateTime of DCP (last Price) sampling (if all shares are up to date, all entries should be the same)',
    'ShareNumber': 'BSB assigned share number',
    'ShareName': 'Fuller name of share',
    'Lazy': 'Activity indication',
    'VP': 'Volume x Price product ie turnover',
    'DCP': 'DAILY Last Price (Close) observed',
    'DOP': 'Last Daily Opening Price observed',
    'DHP': 'Last Daily Highest Price observed',
    'AvMV': 'Average Minute Volume',
    'AvMVdec': 'Average of the (declined) MVm values',
    'PSMV': 'Particular Sum of Minute Volume',
    'CV1': 'Cluster Volume of the day',
    'RCV1': 'Relative Cluster Volume of the day',
    'RCV1small': 'Smallest of RCV1.D-1..RCV.D-5',
    'DLP': 'Last Daily Lowest Price observed',
    'DLOCP': 'Daily Low Open-Close Price: The first (Open) or the last (Close) price, whichever is lower',
    'DHOCP': 'Daily High Open-Close Price: The first (Open) or the last (Close) price, whichever is higher',
    'DMP': 'Daily Middle Price: Middle price between first price and last price of the day, so it is the middle between Open and Close price',
    'DT': 'Daily Turnover on day D: DTD = ODVD * DAPD',
    'DT1': 'Daily Turnover for the 1. Stage on day D: DTD = ODVD * DHPD',
    'SDT': 'Simplified Turnover: DV (Daily Volume, = last figure of any day in the .txt) * DCP (Daily Close Price)',
    'ODV': 'original Daily Volume',
    'DV': 'modified Daily Volume',
    'bSDV': 'backwards Slow Daily Volume' ,
    'RbSDV': 'relation xxx....',
    'HBF': 'Hundred day Broadness Factor',
    'DHPlasthi': 'Highest Daily Highest Price of the last day',
    'DHPlast3hi': 'Highest DHP (Daily Highest Price) of the last 3 days', 
    'DHPlast20hi': 'Highest Daily Highest Price of the last 20 days',
    'DHPlast20hi3perc': 'Highest price of the last 20 days, plus 3%', 

    'DaysDHPlasthi': 'Number of days back since price has been higher than DHPlast3hi',
    'DaysDHPlast20hi': 'Number of days back since price has been higher than DHPlast20hi',
    'DaysDHPlasthi3perc': 'Number of days back since 3% more than DHPlasthi was bettered',

    'DHPlasthi3perc': 'DHPlasthi plus 3%', #new
    'DHPbig': 'Daily High Price of the last 100 days', 
    'DLPsmall': 'smallest Daily Lowest Price of these last 100 days',
    'DHPGr': 'Daily High Price Gradient',
    'DHPGrAvSh': 'Daily High Price Gradient (short)',
    'DHPGrAvMi': 'Daily High Price Gradient (middle)',
    'DHPGrAvLo': 'Daily High Price Gradient (long)',
    'DHPGrDiSl': 'Daily High Price Gradient distance from the long',
    'DHPGrDiF': 'Daily High Price Gradient distance from the short',
    'pnt1_DHPGrDiF': '0.1*DHPGrDiF',
    'pnt3_DHPGrDiF': '0.3*DHPGrDiF',

    'SDVBsl':'Slow Daily Vol Basic slow', 
    'SDVBm':'Slow Daily Vol Basic medium', 
    'SDVBf':'Slow Daily Vol Basic fast', 
    'SDVCsl':'Slow Daily Vol Compare slow', 
    'SDVCm':'Slow Daily Vol Compare medium', 
    'SDVCf1':'Slow Daily Vol Compare fast1', 
    'SDVCf2':'Slow Daily Vol Compare fast2',

    #'DVFdf': 'Daily Vols Figure',
    'DVFf1': 'Daily Vols Figure',
    'DVFf3': 'Daily Vols Figure',
    'DVFm': 'Daily Vols Figure',
    'DVFsl': 'Daily Vols Figure',

    'SRDHP1': 'Slow Relativized Daily Avergae Price1',
    'SRDHP2': 'Slow Relativized Daily Avergae Price2',
    'SRDHP3': 'Slow Relativized Daily Avergae Price3',
    'SRDHP4': 'Slow Relativized Daily Avergae Price4',
    'SRDHP5': 'Slow Relativized Daily Avergae Price5',

    'SRDHPGr1': 'SRDHP1 Price Gradient',
    'SRDHPGr2': 'SRDHP2 Price Gradient',
    'SRDHPGr3': 'SRDHP3 Price Gradient',
    'SRDHPGr4': 'SRDHP4 Price Gradient',

    'SDHP': 'Slow Daily Highest Price',
    'SDHPGr1sh': 'Slow Daily High Prices Gradient (short)',
    'SDHPGr1m': 'Slow Daily High Prices Gradients (middle)',
    'SDHPGr1lo': 'Slow Daily High Prices Gradients (long)',
    'SDT1f': 'Slow Daily Turnover (fast)',
    'SDT1sl': 'Slow Daily Turnover (slow)',
    'DTF': 'Daily Turnover Figure',
    'SDLOCPGrsl': 'Slow Daily Lower Open Close Price Gradient',
    'DLOCup': 'Number of days since when SDLOCPsa was < 1',
    'SBr': 'Slow Broadness',
    'DjP': 'Number of days where DHPD-x/DLOCPD-1-x < 0.4*RDPjPD  was not fulfilled',

    'MSmp': 'Minutely Sight to view more the change of price',
    'MSmpv': 'Minutely Sight to view change of price and vol equally',
    'MSmv': 'Minutely Sight to view more the change of vol',

    'DDHPlasthi': 'Number of days since the DHPlasthigh D was higher than on the last day',
    'DDHPlasthi3perc': 'Number of days since the DHPlasthigh3perc D was higher than on the last day',
    'DDHPlast20hi': 'Number of days since the DHPlast20high D was higher than on the last day',
}
