import pandas as pd
import tabloo

# This is a standalone python script which allows you to view the 'overview'
# generated by the bsbetl utility and housed in an HDFStore

# Important: set overview store path here !!!!
OVERVIEW_STORE_NAME = f'\BsbEtl\OUT\By_Share\OVERVIEWS.h5'


def splash():

    print('IMPORTANT')
    print()
    print('KILL this terminal when browsing the overview is done.')
    print('There is NO alternative way to get back to the prompt ;(')
    print()


def show_overview():
    """ retrieve overview dataframe from HDFStore and get the tabloo viewer to show it"""

    splash()

    data_store = pd.HDFStore(OVERVIEW_STORE_NAME)
    ov_df = data_store['overview']
    data_store.close()

    tabloo.show(ov_df)

    return


if __name__ == '__main__':
    show_overview()
