import sys
import pandas as pd
import tabloo

# This is a standalone python script which allows you to view the 'overview'
# generated by the bsbetl utility and housed in an HDFStore

# Important: set overview store path here !!!!
SHARE_STORE_NAME = f'\BsbEtl\OUT\By_Share\SHARES.h5'


def splash():

    print('IMPORTANT')
    print()
    print('KILL this terminal when browsing is done.')
    print('There is NO alternative way to get back to the prompt ;(')
    print()


def show_share(share_key: str):
    """ retrieve NAMED dataframe from HDFStore and get the tabloo viewer to show it"""

    # example share_key eg ETR_865985
    data_store = pd.HDFStore(SHARE_STORE_NAME)
    try:
        df = data_store[share_key]
        splash()  # dont show if exception thrown
        tabloo.show(df)
    except KeyError as ke:
        print()
        print(f'Key Error {ke}')
        print()
    finally:
        data_store.close()


############################################


if __name__ == '__main__':
    show_share(sys.argv[1])
